# serverless.yml

service: scored-reports

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  environment:
    DYNAMODB_TABLE: report-fetcher-prod
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  app:
    handler: handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'